stages:
  - lint

ruff:
  stage: lint
  image: python:3.12-slim
  script:
    - pip install ruff
    - ruff check src

mypy:
  stage: lint
  image: python:3.12-slim
  script:
    - pip install mypy types-requests types-PyYAML
    - mypy src

pytest:
  stage: lint
  image: python:3.12-slim
  script:
    - pip install pytest
    - pip install -e .
    - pytest tests/
